name: Test

on: [push]

jobs:
    test:
        name: Test

        runs-on: ubuntu-latest

        strategy:
            matrix:
                php-version: '7.3'

        steps:
        - name: Setup PHP ${{ matrix.php-version }}
            uses: actions/checkout@v1

        - name: Run test suite
            run: composer run-script test
